export const CHAIN_CONFIGS = [
	{
		shortName: "shape",
		mainnetName: "shape-mainnet",
		displayName: "Shape",
		mainnetChainId: 360,
		color: "greenBright",
		testnetChainId: 11011,
		testnetChainName: "shape-sepolia",
	},
	{
		shortName: "base",
		displayName: "Base",
		mainnetName: "base-mainnet",
		mainnetChainId: 8453,
		color: "blueBright",
		testnetChainId: 84532,
		testnetChainName: "base-sepolia",
	},
	{
		shortName: "soneium",
		displayName: "Soneium",
		mainnetName: "soneium-mainnet",
		mainnetChainId: 1868,
		color: "greenBright",
		testnetChainId: 1946,
		testnetChainName: "soneium-minato",
	},
	{
		shortName: "unichain",
		displayName: "Unichain",
		mainnetName: "unichain-mainnet",
		mainnetChainId: 130,
		color: "magenta",
		testnetChainId: 1301,
		testnetChainName: "unichain-sepolia",
	},
	{
		shortName: "ink",
		displayName: "Ink",
		mainnetName: "ink-mainnet",
		mainnetChainId: 57073,
		color: "cyan",
		testnetChainId: 57073,
		testnetChainName: "ink-sepolia",
	},
	{
		shortName: "eth",
		displayName: "Ethereum",
		mainnetName: "eth-mainnet",
		mainnetChainId: 1,
		color: "blueBright",
		testnetChainId: 11155111,
		testnetChainName: "eth-sepolia",
	},
	{
		shortName: "opt",
		displayName: "OP Mainnet",
		mainnetName: "opt-mainnet",
		mainnetChainId: 10,
		color: "redBright",
		testnetChainId: 11155420,
		testnetChainName: "opt-sepolia",
	},
	{
		shortName: "polygon",
		displayName: "Polygon",
		mainnetName: "polygon-mainnet",
		mainnetChainId: 137,
		color: "magentaBright",
		testnetChainId: 80001,
		testnetChainName: "polygon-mumbai",
	},
	{
		shortName: "arb",
		displayName: "Arbitrum One",
		mainnetName: "arb-mainnet",
		mainnetChainId: 42161,
		color: "cyanBright",
		testnetChainId: 421614,
		testnetChainName: "arb-sepolia",
	},
	{
		shortName: "monad",
		displayName: "Monad",
		mainnetName: "monad-mainnet",
		mainnetChainId: 143,
		color: "magentaBright",
		testnetChainId: 10143,
		testnetChainName: "monad-testnet",
	},
	{
		shortName: "opbnb",
		displayName: "opBNB",
		mainnetName: "opbnb-mainnet",
		mainnetChainId: 204,
		color: "yellowBright",
		testnetChainId: 5611,
		testnetChainName: "opbnb-testnet",
	},
	{
		shortName: "world",
		mainnetName: "worldchain-mainnet",
		displayName: "World Chain",
		mainnetChainId: 480,
		color: "cyanBright",
		testnetChainId: 4801,
		testnetChainName: "worldchain-sepolia",
	},
];

export const VALID_CHAINS = CHAIN_CONFIGS.map((chain) => chain.shortName);
