export const CHAIN_CONFIGS = [
	{
		mainnetName: "shape",
		mainnetChainId: 360,
		displayName: "Shape",
		color: "greenBright",
		scaffoldConfigId: "shape-chain",
		testnetChainId: 11011,
		testnetChainName: "shape-sepolia",
	},
	{
		mainnetName: "world",
		mainnetChainId: 480,
		displayName: "World",
		color: "cyanBright",
		scaffoldConfigId: "world-chain",
		testnetChainId: 4801,
		testnetChainName: "worldchain-sepolia",
	},
	{
		mainnetName: "monad",
		mainnetChainId: 143,
		displayName: "Monad",
		color: "magentaBright",
		scaffoldConfigId: "monad-chain",
		testnetChainId: 10143,
		testnetChainName: "monad-testnet",
	},
	{
		mainnetName: "opbnb",
		mainnetChainId: 204,
		displayName: "opBNB",
		color: "yellowBright",
		scaffoldConfigId: "opbnb-chain",
		testnetChainId: 5611,
		testnetChainName: "opbnb-testnet",
	},
	{
		mainnetName: "unichain",
		mainnetChainId: 130,
		displayName: "Unichain",
		color: "magenta",
		scaffoldConfigId: "unichain-chain",
		testnetChainId: 1301,
		testnetChainName: "unichain-sepolia",
	},
	{
		mainnetName: "ink",
		displayName: "Ink",
		color: "cyan",
		scaffoldConfigId: "ink-chain",
		testnetChainId: 57073,
		testnetChainName: "ink-sepolia",
	},
	{
		mainnetName: "eth",
		mainnetChainId: 1,
		displayName: "Ethereum",
		color: "blueBright",
		scaffoldConfigId: "eth-chain",
		testnetChainId: 11155111,
		testnetChainName: "eth-sepolia",
	},
	{
		mainnetName: "opt",
		mainnetChainId: 10,
		displayName: "OP Mainnet",
		color: "redBright",
		scaffoldConfigId: "opt-chain",
		testnetChainId: 11155420,
		testnetChainName: "opt-sepolia",
	},
	{
		mainnetName: "matic",
		mainnetChainId: 137,
		displayName: "Polygon PoS",
		color: "magentaBright",
		scaffoldConfigId: "matic-chain",
		testnetChainId: 80001,
		testnetChainName: "polygon-mumbai",
	},
	{
		mainnetName: "arb",
		mainnetChainId: 42161,
		displayName: "Arbitrum",
		color: "cyanBright",
		scaffoldConfigId: "arb-chain",
		testnetChainId: 421614,
		testnetChainName: "arb-sepolia",
	},
	{
		mainnetName: "base",
		mainnetChainId: 8453,
		displayName: "Base",
		color: "blueBright",
		scaffoldConfigId: "base-chain",
		testnetChainId: 84532,
		testnetChainName: "base-sepolia",
	},
	{
		mainnetName: "soneium",
		mainnetChainId: 1868,
		displayName: "Soneium",
		color: "greenBright",
		scaffoldConfigId: "soneium-chain",
		testnetChainId: 1946,
		testnetChainName: "soneium-minato",
	},
];

export const VALID_CHAINS = CHAIN_CONFIGS.map((chain) => chain.mainnetName);
